title: HackOverflow
markdown: kramdown
url: "http://hackoverflow.org"
#baseurl: ""
# for atom feed
author:
  name: HackOverflow
  email: help@hackoverflow.org

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  #- jekyll-paginate
  #- jekyll/tagging

# collections
collections_dir: all_collections
collections:
  posts:
    output: true


# page path
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
